version: '3.8'

services:
  app:
    image: php:8.3-fpm
    container_name: symfony-app
    volumes:
      - ./${PROJECT_DIR}:/var/www/project
    working_dir: /var/www/project
    networks:
      - symfony-network

  web:
    image: nginx:latest
    container_name: symfony-web
    ports:
      - "8080:80"
    volumes:
      - ./${PROJECT_DIR}:/var/www/project
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony-network

  db:
    image: mysql:8.0
    container_name: symfony-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - symfony-network

volumes:
  mysql-data:

networks:
  symfony-network:
    driver: bridge
